T2D-267 google OAuth for properties Registry
EBIvariation/amp-t2d-property-registry pull request #9
Opened 2018-11-19 14:12 UTC by selvaebi

2018-11-21 23:14 UTC, Zhicheng-Liu requested changes

2018-11-21 23:14 UTC, Zhicheng-Liu commented on src/main/java/uk/ac/ebi/ampt2d/registry/entities/User.java
> +    public enum Roles {
`Role`, singular form for class names.

2018-11-21 23:14 UTC, Zhicheng-Liu commented on src/test/java/uk/ac/ebi/ampt2d/registry/PropertyRegistryServiceApplicationTests.java
> +        mockMvc.perform(get("/swagger-ui.html")).andExpect(status().isOk()); // Swagger is not secured
For completeness, could you test all the URLs in the whitelist?

2018-11-21 23:14 UTC, Zhicheng-Liu commented on src/test/java/uk/ac/ebi/ampt2d/registry/PropertyRegistryServiceApplicationTests.java
> +                .content(content)).andExpect(status().isCreated());
For completeness, I would also add test cases for other request methods and roles combinations.

2018-11-22 11:32 UTC, Zhicheng-Liu approved these changes

2018-11-26 09:40 UTC, iyangar requested changes

2018-11-26 09:40 UTC, iyangar commented on src/test/resources/application.properties
> +registry.protocols=http
Do you mean `https`?

2018-11-26 09:51 UTC, selvaebi commented on src/test/resources/application.properties
> +registry.protocols=http
no test uses http

2018-11-26 09:54 UTC, iyangar commented on src/test/resources/application.properties
> +registry.protocols=http
ok, fine. same line was deleted and added again, hence got clarified

2018-11-26 09:55 UTC, iyangar approved these changes

2018-11-29 10:26 UTC, merged